name: Maven Package

# https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#pull_request
on: [push]
# on:
  # PRがオープン、再オープンされた時、PRのヘッドが更新された場合実行
  # pull_request:
    # types: [ opened, synchronize, reopened ]
    # PRターゲットブランチでフィルターする場合
    # branches: [ master, main, releases/** ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      # packages: write
      # checks: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        # server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        # settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # JUnitテスト結果レポートを作成
    # https://github.com/marketplace/actions/junit-report-action
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: 'target/surefire-reports/TEST-*.xml'
        # annotate_only: true
        # token: ${{ github.token }}

    # - name: Publish to GitHub Packages Apache Maven
    #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}

